title: <p align="center"> Aenun Hardianingsih </p>

logo: "Desain tanpa judul_1.png"

description:
  <p align="center">
  <a href="CV ATS - Aenun Hardianingsh.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/aenunh/">LinkedIn</a> |
  <a href="https://github.com/aenunh">GitHub</a>
  </p>
  
  <p align="justify">
  hi i'am currently studying at Universitas Swadaya Gunung Jati bachelor of accounting
    <br><br>
  has an interest in the field of data analytics and is still developing capabilities in that field. 
   <br><br>
  </p>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
